---
- name: Installing apache2 on ubuntu
  hosts: all
  become: yes
  tasks: 
    - name: installing apache2
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true
    - name: installing php
      ansible.builtin.apt:
        name: php
        state: present
    - name: source & destination      
      ansible.builtin.copy:    
        src: info.php
        dest: /var/www/html/info.php
  
